### ISSUE TITLE
[BUG] Comment edit save fails to display updated content

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#61]
**Describe the bug**
Blog post owner edits own comment and comment edit save fails to display updated content.

**To Reproduce**
1. Go to a comment that the currently logged in user owns and click on the Dropdown Menu.
2. Choose the edit option and the edit form will show up.
3. If you choose to make an edit and click save, the updated version of that comment will show up.
```
Error: Request failed with status code 400
    at createError (createError.js:16:1)
    at settle (settle.js:17:1)
    at XMLHttpRequest.onloadend (xhr.js:54:1)
```

**Expected behavior**
If you choose to make an edit and click save, the updated version of that comment will show up.

**Screenshots**
n/a

**Desktop / Smartphone** (please complete the following information):**
- Desktop
- Chrome Version 125.0.6422.141 (Official Build) (64-bit)

**Additional context**
Found during development the Frontend part of of comments function.

**Comment by JaqiKal** [comment]
Solution: In pixavibe-api, app comments, views.py, to import missing var CommentDetailSerializer and update incorrect var in class commentDetail.
